server:
  port: 8089
spring:
  application:
    name: hiklog
  rabbitmq:  
      host: localhost
      port: 5672
      username: admin
      password: 520131
  redis:
    host: localhost
    port: 6379
    password: 520131
    jedis:
      pool:
        max-active: 50
        max-idle: 20
        max-wait: 60000
