server:
  port: 8089
spring:
  application:
    name: hiklog
  rabbitmq:  
      host: 192.168.1.7
      port: 5672
      username: admin
      password: 520131
  data:
    elasticsearch:
      cluster-name: elasticsearch_apple
      cluster-nodes: 127.0.0.1:9300 #9300java的客户端
      spring:
        data:
          elasticsearch:
            properties:
              path:
                home: /data/project/target/elastic
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 50
        max-idle: 20
        max-wait: 60000              
