server:
  port: 8084
  servlet:
    session:
      timeout: 80000
spring:
  application:
    name: member
  datasource:
    username: root
    password: 520131D.
    url: jdbc:mysql://localhost:3306/life_member?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    consul:
      port: 8500
  rabbitmq:  
    host: localhost
    port: 5672
    username: admin
    password: 520131    
mybatis:
  mapper-locations: classpath:mapping/Mapper*.xml
  type-aliases-package: com.member.bootstrap.model
  config-location: classpath:mybatis-config.xml
pagehelper:
  auto-dialect:
  helper-dialect: MYSQL
  reasonable: true
  support-methods-arguments: true
